apiVersion: v1
kind: Service
metadata:
  name: miniblog
spec:
  type: LoadBalancer
  selector:
    app: miniblog
  ports:
    - port: 88
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: miniblog
spec:
  selector:
    matchLabels:
      app: miniblog
  template:
    metadata:
      labels:
        app: miniblog
    spec:
      containers:
        - name: miniblog
          image: rj0510/miniblog-front:0.1.0
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 88