apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - port: 5432
      nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
        - name: init-db-config-map
          configMap:
            name: init-db
      containers:
        - name: postgres
          image: postgres:14
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: init-db-config-map
              mountPath: /docker-entrypoint-initdb.d
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: init-db
data:
  db.sql: |
    CREATE TABLE USERS (
      USER_ID VARCHAR(150) PRIMARY KEY,
      EMAIL VARCHAR(150) NOT NULL
    );

    CREATE TABLE BANK_ACCOUNTS (
      ACCOUNT_ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
      ACCOUNT_NAME VARCHAR(25) NOT NULL,
      USER_ID VARCHAR(150) NOT NULL REFERENCES USERS(USER_ID)
    );

    CREATE TABLE CATEGORIES_TYPE (
      CATEGORY_TYPE_ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
      CATEGORY_TYPE VARCHAR(25) NOT NULL
    );

    CREATE TABLE CATEGORIES (
      CATEGORY_ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
      CATEGORY VARCHAR(25) NOT NULL,
      CATEGORY_TYPE_ID INT NOT NULL REFERENCES CATEGORIES_TYPE(CATEGORY_TYPE_ID),
      USER_ID VARCHAR(150) NOT NULL REFERENCES USERS(USER_ID)
    );

    CREATE TABLE TRANSACTIONS (
      TRANSACTION_ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
      AMOUNT NUMERIC(11, 2) NOT NULL,
      TRANSACTION_DATE DATE NOT NULL,
      CATEGORY_ID INT NOT NULL REFERENCES CATEGORIES(CATEGORY_ID),
      ACCOUNT_ID INT NOT NULL REFERENCES BANK_ACCOUNTS(ACCOUNT_ID),
      USER_ID VARCHAR(150) NOT NULL REFERENCES USERS(USER_ID)
    );

    INSERT INTO CATEGORIES_TYPE (CATEGORY_TYPE) VALUES ('Income');
    INSERT INTO CATEGORIES_TYPE (CATEGORY_TYPE) VALUES ('Expenses');
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
data:
  password: YWRtaW4K
type: Opaque
